alldata ={'2019-11-08': {'2020考研英语冲刺·体验版': {'buy_num': 1,
                                   'courseName': '2020考研英语冲刺·体验版',
                                   'coursePrice': 1.0},
                '像北大学霸一样思考3.0': {'buy_num': 23,
                                 'courseName': '像北大学霸一样思考3.0',
                                 'coursePrice': 16.0},
                '原生家庭背锅指南': {'buy_num': 1,
                             'courseName': '原生家庭背锅指南',
                             'coursePrice': 1.0},
                '孤阅万国·学术西班牙语': {'buy_num': 1,
                                'courseName': '孤阅万国·学术西班牙语',
                                'coursePrice': 1900.0}},
 '2019-11-09': {'2020考研英语冲刺·体验版': {'buy_num': 25,
                                   'courseName': '2020考研英语冲刺·体验版',
                                   'coursePrice': 25.0},
                '像北大学霸一样思考3.0': {'buy_num': 388,
                                 'courseName': '像北大学霸一样思考3.0',
                                 'coursePrice': 336.0},
                '原生家庭背锅指南': {'buy_num': 33,
                             'courseName': '原生家庭背锅指南',
                             'coursePrice': 33.0},
                '如何快速学好一门语言3.0': {'buy_num': 8,
                                  'courseName': '如何快速学好一门语言3.0',
                                  'coursePrice': 8.0},
                '孤独的阅读者': {'buy_num': 10,
                           'courseName': '孤独的阅读者',
                           'coursePrice': 0.0},
                '孤阅·2020燎原官方预售群': {'buy_num': 12,
                                   'courseName': '孤阅·2020燎原官方预售群',
                                   'coursePrice': 2400.0},
                '孤阅·PORTA·学神工具包': {'buy_num': 2,
                                   'courseName': '孤阅·PORTA·学神工具包',
                                   'coursePrice': 808.0},
                '孤阅·帕勒芒': {'buy_num': 1,
                           'courseName': '孤阅·帕勒芒',
                           'coursePrice': 0.0},
                '孤阅万国·学术法语': {'buy_num': 1,
                              'courseName': '孤阅万国·学术法语',
                              'coursePrice': 3300.0},
                '孤阅万国·学术法语定金群': {'buy_num': 3,
                                 'courseName': '孤阅万国·学术法语定金群',
                                 'coursePrice': 240.0},
                '孤阅万国·学术西班牙语': {'buy_num': 1,
                                'courseName': '孤阅万国·学术西班牙语',
                                'coursePrice': 1900.0},
                '孤阅帕勒芒·拓荒者': {'buy_num': 1,
                              'courseName': '孤阅帕勒芒·拓荒者',
                              'coursePrice': 0.0},
                '批判性思维夏季攻势': {'buy_num': 2,
                              'courseName': '批判性思维夏季攻势',
                              'coursePrice': 19.8},
                '法西德 15 日通关密营': {'buy_num': 34,
                                 'courseName': '法西德 15 日通关密营',
                                 'coursePrice': 34.0},
                '送给年轻人的幸福课': {'buy_num': 5,
                              'courseName': '送给年轻人的幸福课',
                              'coursePrice': 145.0}},
 '2019-11-10': {'2020考研英语冲刺·体验版': {'buy_num': 2,
                                   'courseName': '2020考研英语冲刺·体验版',
                                   'coursePrice': 198.0},
                '像北大学霸一样思考3.0': {'buy_num': 329,
                                 'courseName': '像北大学霸一样思考3.0',
                                 'coursePrice': 286.0},
                '原生家庭背锅指南': {'buy_num': 35,
                             'courseName': '原生家庭背锅指南',
                             'coursePrice': 35.0},
                '哲学大问题 2.0': {'buy_num': 2,
                              'courseName': '哲学大问题 2.0',
                              'coursePrice': 20.0},
                '如何快速学好一门语言3.0': {'buy_num': 10,
                                  'courseName': '如何快速学好一门语言3.0',
                                  'coursePrice': 10.0},
                '如何快速学好英语': {'buy_num': 1,
                             'courseName': '如何快速学好英语',
                             'coursePrice': 99.0},
                '孤独的阅读者': {'buy_num': 12,
                           'courseName': '孤独的阅读者',
                           'coursePrice': 0.0},
                '孤阅·2020燎原官方预售群': {'buy_num': 13,
                                   'courseName': '孤阅·2020燎原官方预售群',
                                   'coursePrice': 2600.0},
                '孤阅·PORTA·学神工具包': {'buy_num': 1,
                                   'courseName': '孤阅·PORTA·学神工具包',
                                   'coursePrice': 404.0},
                '孤阅万国·学术西班牙语': {'buy_num': 1,
                                'courseName': '孤阅万国·学术西班牙语',
                                'coursePrice': 2200.0},
                '孤阅万国·学术西班牙语定金群': {'buy_num': 1,
                                   'courseName': '孤阅万国·学术西班牙语定金群',
                                   'coursePrice': 80.0},
                '批判性思维夏季攻势': {'buy_num': 2,
                              'courseName': '批判性思维夏季攻势',
                              'coursePrice': 19.8},
                '法西德 15 日通关密营': {'buy_num': 31,
                                 'courseName': '法西德 15 日通关密营',
                                 'coursePrice': 31.0},
                '送给年轻人的幸福课': {'buy_num': 8,
                              'courseName': '送给年轻人的幸福课',
                              'coursePrice': 232.0}}}
